{% set name = "openff-qcsubmit" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-qcsubmit/archive/{{ version }}.tar.gz
  sha256: 781e93e8e99e7689ff0b30bf1bd785884793d394da82790a905ecf12155c4c40

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - qcportal
    - openff-toolkit-base >=0.10.6,<0.11.0a0
    - rdkit
    - pyyaml
    - pydantic
    - basis_set_exchange
    - typing-extensions
    - cachetools

test:
  imports:
    - openff.qcsubmit

about:
  home: https://github.com/openforcefield/openff-qcsubmit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Automated tools for submitting molecules to QCFractal'
  description: |
    The OpenFF QCSubmit framework aims to facilitate curating and contributing
    new quantum chemical (QC) datasets to the QCArchive (or any other QCFractal instance),
    as well as to retrieve already computed datasets.
  doc_url: https://openff-qcsubmit.readthedocs.io
  dev_url: https://github.com/openforcefield/openff-qcsubmit

extra:
  recipe-maintainers:
    - JTHorton
    - SimonBoothroyd
    - j-wags
    - dotsdl
    - mattwthompson
