{% set name = "openff-qcsubmit" %}
{% set version = "0.54.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-qcsubmit/archive/{{ version }}.tar.gz
  sha256: 858fff536df133019e0fe1a84f2f072e24f50108f34ca4730d767d0d9d7c8229

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - tqdm
    - networkx
    # context https://github.com/MolSSI/QCElemental/issues/323#issuecomment-2297528477
    - qcelemental <=0.28
    - qcportal >=0.54
    - openff-toolkit-base >=0.12
    - rdkit
    - pyyaml
    - pydantic <3.0.0a0
    - basis_set_exchange
    - typing_extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - openff.qcsubmit

about:
  home: https://github.com/openforcefield/openff-qcsubmit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automated tools for submitting molecules to QCFractal
  description: |
    The OpenFF QCSubmit framework aims to facilitate curating and contributing
    new quantum chemical (QC) datasets to the QCArchive (or any other QCFractal instance),
    as well as to retrieve already computed datasets.
  doc_url: https://openff-qcsubmit.readthedocs.io
  dev_url: https://github.com/openforcefield/openff-qcsubmit

extra:
  recipe-maintainers:
    - JTHorton
    - SimonBoothroyd
    - j-wags
    - dotsdl
    - mattwthompson
