{% set name = "openff-qcsubmit" %}
{% set version = "0.50.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-qcsubmit/archive/{{ version }}.tar.gz
  sha256: f642eccb803f5db07c9d87c998a7378a125abc7c27d594ed1a3d79c243fe4e0b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - qcportal >=0.49
    - openff-toolkit-base >=0.12
    - rdkit
    - pyyaml
    - pydantic <2.0.0a0
    - basis_set_exchange
    - typing_extensions

test: 
  imports:
    - openff.qcsubmit

about:
  home: https://github.com/openforcefield/openff-qcsubmit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automated tools for submitting molecules to QCFractal
  description: |
    The OpenFF QCSubmit framework aims to facilitate curating and contributing
    new quantum chemical (QC) datasets to the QCArchive (or any other QCFractal instance),
    as well as to retrieve already computed datasets.
  doc_url: https://openff-qcsubmit.readthedocs.io
  dev_url: https://github.com/openforcefield/openff-qcsubmit

extra:
  recipe-maintainers:
    - JTHorton
    - SimonBoothroyd
    - j-wags
    - dotsdl
    - mattwthompson
